-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 13:30:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema kebabownia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kebabownia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kebabownia` ;
USE `kebabownia` ;

-- -----------------------------------------------------
-- Table `Kebab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kebab` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  `rozmiar` VARCHAR(45) NOT NULL,
  `cena` DOUBLE NOT NULL,
  `mieso` VARCHAR(45) NOT NULL,
  `sos` VARCHAR(45) NOT NULL,
  `czyAktywne` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idKebab_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Turek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Turek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `stanowisko` VARCHAR(45) NOT NULL,
  `stawka_godzinowa` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTurek_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Paragon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Paragon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Turek_id` INT NOT NULL,
  `Kebab_id` INT NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `kod_pocztowy` VARCHAR(45) NOT NULL,
  `suma` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idParagon_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Paragon_Turek1_idx` (`Turek_id` ASC) VISIBLE,
  INDEX `fk_Paragon_Kebab1_idx` (`Kebab_id` ASC) VISIBLE,
  CONSTRAINT `fk_Paragon_Turek1`
    FOREIGN KEY (`Turek_id`)
    REFERENCES `Turek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paragon_Kebab1`
    FOREIGN KEY (`Kebab_id`)
    REFERENCES `Kebab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uzytkownik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(100) NOT NULL,
  `rola` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTurek_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
