spring:
  datasource: #database connection
    url: jdbc:mysql://localhost:3307/kebabownia
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
   name: project
  main:
    banner-mode: off

# server:
#   port: 8081

logging:
  level.root: warn
