spring:
  datasource: #database connection
    url: jdbc:mysql://localhost:3307/kebabownia
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
   name: project
  main:
    banner-mode: off
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# server:
  # port: 8081

logging:
  level.root: warn
