spring:
  datasource: #database connection
    url: jdbc:mysql://localhost:3307/kebabownia
    username: user
    password: pass

  application:
   name: project
  main:
    banner-mode: off


logging:
  level.root: warn
